#!/bin/sh
mvn clean package && docker build -t bhavin1324/OrderingService .
docker rm -f OrderingService 2>/dev/null || true && docker run -it --name OrderingService -p 8080:8080 -p 4848:4848 -p 8181:8181 --name OrderingService bhavin1324/OrderingService
