#!/bin/sh
mvn clean package && docker build -t bhavin1324/CustomerService .
docker rm -f CustomerService 2>/dev/null || true && docker run -it --name CustomerService -p 8080:8080 -p 4848:4848 -p 8181:8181 --name CustomerService bhavin1324/CustomerService
