#!/bin/sh
mvn clean package && docker build -t bhavin1324/DeliveryService .
docker rm -f DeliveryService 2>/dev/null || true && docker run -it --name DeliveryService -p 8080:8080 -p 4848:4848 -p 8181:8181 --name DeliveryService bhavin1324/DeliveryService
