#!/bin/sh
mvn clean package && docker build -t bhavin1324/PreparationService .
docker rm -f PreparationService 2>/dev/null || true && docker run -it --name PreparationService -p 8080:8080 -p 4848:4848 -p 8181:8181 --name PreparationService bhavin1324/PreparationService
